### ISSUE TITLE
npm package name

### ISSUE THREAD

**Issue by callumacrae** [Julow/SpeedTest#1]
Hey!

Do you have any plans to use this library in the future? It looks like nobody is using the speedtest package on npm, and I'm writing a speed test at the moment - it would be super great if we could use the speedtest package name on npm!

Of course, it would be published a major version up from your library so that if anybody is using it, it won't break their apps.

Cheers :)

**Comment by Julow** [comment]
OK
Should I remove it from npm ?

**Comment by callumacrae** [comment]
I don't think you can remove it: I think the normal way is to add me as an owner: https://docs.npmjs.com/cli/owner

```
npm owner add callumacrae speedtest
```

Then I'll remove you, and use a major version bump for my package :)

thanks!

**Comment by Julow** [comment]
Installing npm...

...

done

**Comment by callumacrae** [comment]
Amazing, thank you so much! 😄
